<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Análise de Dados Amostrais Complexos</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Análise de dados de pesquisas amostrais complexas.">
  <meta name="generator" content="bookdown 0.3 and GitBook 2.6.7">

  <meta property="og:title" content="Análise de Dados Amostrais Complexos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="Figuras/capa.png" />
  <meta property="og:description" content="Análise de dados de pesquisas amostrais complexas." />
  <meta name="github-repo" content="djalmapessoa/adac" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Análise de Dados Amostrais Complexos" />
  
  <meta name="twitter:description" content="Análise de dados de pesquisas amostrais complexas." />
  <meta name="twitter:image" content="Figuras/capa.png" />

<meta name="author" content="Djalma Pessoa e Pedro Nascimento Silva">


<meta name="date" content="2017-04-25">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="refinf.html">
<link rel="next" href="epa.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análise de Dados Amostrais Complexos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#agradecimentos"><i class="fa fa-check"></i>Agradecimentos</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduc.html"><a href="introduc.html"><i class="fa fa-check"></i><b>1</b> Introdução</a><ul>
<li class="chapter" data-level="1.1" data-path="introduc.html"><a href="introduc.html#motivacao"><i class="fa fa-check"></i><b>1.1</b> Motivação</a></li>
<li class="chapter" data-level="1.2" data-path="introduc.html"><a href="introduc.html#objetivos-do-livro"><i class="fa fa-check"></i><b>1.2</b> Objetivos do Livro</a></li>
<li class="chapter" data-level="1.3" data-path="introduc.html"><a href="introduc.html#epa"><i class="fa fa-check"></i><b>1.3</b> Laboratório de R do Capítulo 1.</a><ul>
<li class="chapter" data-level="1.3.1" data-path="introduc.html"><a href="introduc.html#estimativa-do-efeito-de-plano-amostral-epa"><i class="fa fa-check"></i><b>1.3.1</b> Estimativa do efeito de plano amostral (EPA)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="refinf.html"><a href="refinf.html"><i class="fa fa-check"></i><b>2</b> Referencial para Inferência</a><ul>
<li class="chapter" data-level="2.1" data-path="refinf.html"><a href="refinf.html#classic"><i class="fa fa-check"></i><b>2.1</b> Modelagem - Primeiras Idéias</a><ul>
<li class="chapter" data-level="2.1.1" data-path="refinf.html"><a href="refinf.html#abordagem-1---modelagem-classica"><i class="fa fa-check"></i><b>2.1.1</b> Abordagem 1 - Modelagem Clássica</a></li>
<li class="chapter" data-level="2.1.2" data-path="refinf.html"><a href="refinf.html#abordagem-2---amostragem-probabilistica"><i class="fa fa-check"></i><b>2.1.2</b> Abordagem 2 - Amostragem Probabilística</a></li>
<li class="chapter" data-level="2.1.3" data-path="refinf.html"><a href="refinf.html#discussao-das-abordagens-1-e-2"><i class="fa fa-check"></i><b>2.1.3</b> Discussão das Abordagens 1 e 2</a></li>
<li class="chapter" data-level="2.1.4" data-path="refinf.html"><a href="refinf.html#modelsuperpop"><i class="fa fa-check"></i><b>2.1.4</b> Abordagem 3 - Modelagem de Superpopulação</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="refinf.html"><a href="refinf.html#fontes-de-variacao"><i class="fa fa-check"></i><b>2.2</b> Fontes de Variação</a></li>
<li class="chapter" data-level="2.3" data-path="refinf.html"><a href="refinf.html#modelos-de-superpopulacao"><i class="fa fa-check"></i><b>2.3</b> Modelos de Superpopulação</a></li>
<li class="chapter" data-level="2.4" data-path="refinf.html"><a href="refinf.html#planamo"><i class="fa fa-check"></i><b>2.4</b> Planejamento Amostral</a></li>
<li class="chapter" data-level="2.5" data-path="refinf.html"><a href="refinf.html#inform"><i class="fa fa-check"></i><b>2.5</b> Planos Amostrais Informativos e Ignoráveis</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="capplanamo.html"><a href="capplanamo.html"><i class="fa fa-check"></i><b>3</b> Estimação Baseada no Plano Amostral</a><ul>
<li class="chapter" data-level="3.1" data-path="capplanamo.html"><a href="capplanamo.html#estimatotais"><i class="fa fa-check"></i><b>3.1</b> Estimação de Totais</a></li>
<li class="chapter" data-level="3.2" data-path="capplanamo.html"><a href="capplanamo.html#por-que-estimar-variancias"><i class="fa fa-check"></i><b>3.2</b> Por que Estimar Variâncias</a></li>
<li class="chapter" data-level="3.3" data-path="capplanamo.html"><a href="capplanamo.html#taylor"><i class="fa fa-check"></i><b>3.3</b> Linearização de Taylor para Estimar variâncias</a></li>
<li class="chapter" data-level="3.4" data-path="capplanamo.html"><a href="capplanamo.html#metodo-do-conglomerado-primario"><i class="fa fa-check"></i><b>3.4</b> Método do Conglomerado Primário</a></li>
<li class="chapter" data-level="3.5" data-path="capplanamo.html"><a href="capplanamo.html#metodos-de-replicacao"><i class="fa fa-check"></i><b>3.5</b> Métodos de Replicação</a></li>
<li class="chapter" data-level="3.6" data-path="capplanamo.html"><a href="capplanamo.html#laboratorio-de-r"><i class="fa fa-check"></i><b>3.6</b> Laboratório de R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduc.html"><a href="introduc.html#epa"><i class="fa fa-check"></i><b>4</b> Efeitos do Plano Amostral</a><ul>
<li class="chapter" data-level="4.1" data-path="epa.html"><a href="epa.html"><i class="fa fa-check"></i><b>4.1</b> Introdução</a></li>
<li class="chapter" data-level="4.2" data-path="epa.html"><a href="epa.html#efeito-do-plano-amostral-epa-de-kish"><i class="fa fa-check"></i><b>4.2</b> Efeito do Plano Amostral (EPA) de Kish</a></li>
<li class="chapter" data-level="4.3" data-path="epa.html"><a href="epa.html#efeito-do-plano-amostral-ampliado"><i class="fa fa-check"></i><b>4.3</b> Efeito do Plano Amostral Ampliado</a></li>
<li class="chapter" data-level="4.4" data-path="epa.html"><a href="epa.html#intervalos-de-confianca-e-testes-de-hipoteses"><i class="fa fa-check"></i><b>4.4</b> Intervalos de Confiança e Testes de Hipóteses</a></li>
<li class="chapter" data-level="4.5" data-path="epa.html"><a href="epa.html#efeitos-multivariados-de-plano-amostral"><i class="fa fa-check"></i><b>4.5</b> Efeitos Multivariados de Plano Amostral</a></li>
<li class="chapter" data-level="4.6" data-path="epa.html"><a href="epa.html#laboratorio-de-r-1"><i class="fa fa-check"></i><b>4.6</b> Laboratório de R</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ajmodpar.html"><a href="ajmodpar.html"><i class="fa fa-check"></i><b>5</b> Ajuste de Modelos Paramétricos</a><ul>
<li class="chapter" data-level="5.1" data-path="ajmodpar.html"><a href="ajmodpar.html#modpar1"><i class="fa fa-check"></i><b>5.1</b> Introdução</a></li>
<li class="chapter" data-level="5.2" data-path="ajmodpar.html"><a href="ajmodpar.html#metodo-de-maxima-verossimilhanca-mv"><i class="fa fa-check"></i><b>5.2</b> Método de Máxima Verossimilhança (MV)</a></li>
<li class="chapter" data-level="5.3" data-path="ajmodpar.html"><a href="ajmodpar.html#ponderacao-de-dados-amostrais"><i class="fa fa-check"></i><b>5.3</b> Ponderação de Dados Amostrais</a></li>
<li class="chapter" data-level="5.4" data-path="ajmodpar.html"><a href="ajmodpar.html#modpar3"><i class="fa fa-check"></i><b>5.4</b> Método de Máxima Pseudo-Verossimilhança</a></li>
<li class="chapter" data-level="5.5" data-path="ajmodpar.html"><a href="ajmodpar.html#robustez-do-procedimento-mpv"><i class="fa fa-check"></i><b>5.5</b> Robustez do Procedimento MPV</a></li>
<li class="chapter" data-level="5.6" data-path="ajmodpar.html"><a href="ajmodpar.html#desvantagens-da-inferencia-de-aleatorizacao"><i class="fa fa-check"></i><b>5.6</b> Desvantagens da Inferência de Aleatorização</a></li>
<li class="chapter" data-level="5.7" data-path="ajmodpar.html"><a href="ajmodpar.html#laboratorio-de-r-2"><i class="fa fa-check"></i><b>5.7</b> Laboratório de R</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modreg.html"><a href="modreg.html"><i class="fa fa-check"></i><b>6</b> Modelos de Regressão</a><ul>
<li class="chapter" data-level="6.1" data-path="modreg.html"><a href="modreg.html#modlinear"><i class="fa fa-check"></i><b>6.1</b> Modelo de Regressão Linear Normal</a><ul>
<li class="chapter" data-level="6.1.1" data-path="modreg.html"><a href="modreg.html#especificacao-do-modelo"><i class="fa fa-check"></i><b>6.1.1</b> Especificação do Modelo</a></li>
<li class="chapter" data-level="6.1.2" data-path="modreg.html"><a href="modreg.html#pseudo-parametros-do-modelo"><i class="fa fa-check"></i><b>6.1.2</b> Pseudo-parâmetros do Modelo</a></li>
<li class="chapter" data-level="6.1.3" data-path="modreg.html"><a href="modreg.html#estimadores-de-mpv-dos-parametros-do-modelo"><i class="fa fa-check"></i><b>6.1.3</b> Estimadores de MPV dos Parâmetros do Modelo</a></li>
<li class="chapter" data-level="6.1.4" data-path="modreg.html"><a href="modreg.html#estimacao-da-variancia-de-estimadores-de-mpv"><i class="fa fa-check"></i><b>6.1.4</b> Estimação da Variância de Estimadores de MPV</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="modreg.html"><a href="modreg.html#modlogist"><i class="fa fa-check"></i><b>6.2</b> Modelo de Regressão Logística</a></li>
<li class="chapter" data-level="6.3" data-path="modreg.html"><a href="modreg.html#teste-de-hipoteses"><i class="fa fa-check"></i><b>6.3</b> Teste de Hipóteses</a></li>
<li class="chapter" data-level="6.4" data-path="modreg.html"><a href="modreg.html#laboratorio-de-r-3"><i class="fa fa-check"></i><b>6.4</b> Laboratório de R</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="testqualajust.html"><a href="testqualajust.html"><i class="fa fa-check"></i><b>7</b> Testes de Qualidade de Ajuste</a><ul>
<li class="chapter" data-level="7.1" data-path="testqualajust.html"><a href="testqualajust.html#introducao-1"><i class="fa fa-check"></i><b>7.1</b> Introdução</a></li>
<li class="chapter" data-level="7.2" data-path="testqualajust.html"><a href="testqualajust.html#teste-para-uma-proporcao"><i class="fa fa-check"></i><b>7.2</b> Teste para uma Proporção</a><ul>
<li class="chapter" data-level="7.2.1" data-path="testqualajust.html"><a href="testqualajust.html#correcao-de-estatisticas-classicas"><i class="fa fa-check"></i><b>7.2.1</b> Correção de Estatísticas Clássicas</a></li>
<li class="chapter" data-level="7.2.2" data-path="testqualajust.html"><a href="testqualajust.html#estatistica-de-wald"><i class="fa fa-check"></i><b>7.2.2</b> Estatística de Wald</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="testqualajust.html"><a href="testqualajust.html#teste-para-varias-proporcoes"><i class="fa fa-check"></i><b>7.3</b> Teste para Várias Proporções</a><ul>
<li class="chapter" data-level="7.3.1" data-path="testqualajust.html"><a href="testqualajust.html#estatistica-de-wald-baseada-no-plano-amostral"><i class="fa fa-check"></i><b>7.3.1</b> Estatística de Wald Baseada no Plano Amostral</a></li>
<li class="chapter" data-level="7.3.2" data-path="testqualajust.html"><a href="testqualajust.html#situacoes-instaveis"><i class="fa fa-check"></i><b>7.3.2</b> Situações Instáveis</a></li>
<li class="chapter" data-level="7.3.3" data-path="testqualajust.html"><a href="testqualajust.html#raoscott"><i class="fa fa-check"></i><b>7.3.3</b> Estatística de Pearson com Ajuste de Rao-Scott</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="testqualajust.html"><a href="testqualajust.html#laboratorio-de-r-4"><i class="fa fa-check"></i><b>7.4</b> Laboratório de R</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="testetab2.html"><a href="testetab2.html"><i class="fa fa-check"></i><b>8</b> Testes em Tabelas de Duas Entradas</a><ul>
<li class="chapter" data-level="8.1" data-path="testetab2.html"><a href="testetab2.html#introducao-2"><i class="fa fa-check"></i><b>8.1</b> Introdução</a></li>
<li class="chapter" data-level="8.2" data-path="testetab2.html"><a href="testetab2.html#tabelas22"><i class="fa fa-check"></i><b>8.2</b> Tabelas 2x2</a><ul>
<li class="chapter" data-level="8.2.1" data-path="testetab2.html"><a href="testetab2.html#teste-de-independencia"><i class="fa fa-check"></i><b>8.2.1</b> Teste de Independência</a></li>
<li class="chapter" data-level="8.2.2" data-path="testetab2.html"><a href="testetab2.html#teste-de-homogeneidade"><i class="fa fa-check"></i><b>8.2.2</b> Teste de Homogeneidade</a></li>
<li class="chapter" data-level="8.2.3" data-path="testetab2.html"><a href="testetab2.html#efeitos-de-plano-amostral-nas-celas"><i class="fa fa-check"></i><b>8.2.3</b> Efeitos de Plano Amostral nas Celas</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="testetab2.html"><a href="testetab2.html#tabelas-de-duas-entradas-caso-geral"><i class="fa fa-check"></i><b>8.3</b> Tabelas de Duas Entradas (Caso Geral)</a><ul>
<li class="chapter" data-level="8.3.1" data-path="testetab2.html"><a href="testetab2.html#teste-de-homogeneidade-1"><i class="fa fa-check"></i><b>8.3.1</b> Teste de Homogeneidade</a></li>
<li class="chapter" data-level="8.3.2" data-path="testetab2.html"><a href="testetab2.html#teste-de-independencia-1"><i class="fa fa-check"></i><b>8.3.2</b> Teste de Independência</a></li>
<li class="chapter" data-level="8.3.3" data-path="testetab2.html"><a href="testetab2.html#estatistica-de-wald-baseada-no-plano-amostral-1"><i class="fa fa-check"></i><b>8.3.3</b> Estatística de Wald Baseada no Plano Amostral</a></li>
<li class="chapter" data-level="8.3.4" data-path="testetab2.html"><a href="testetab2.html#estatistica-de-pearson-com-ajuste-de-rao-scott"><i class="fa fa-check"></i><b>8.3.4</b> Estatística de Pearson com Ajuste de Rao-Scott</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="testetab2.html"><a href="testetab2.html#laboratorio-de-r-5"><i class="fa fa-check"></i><b>8.4</b> Laboratório de R</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="estimacao-de-densidades.html"><a href="estimacao-de-densidades.html"><i class="fa fa-check"></i><b>9</b> Estimação de densidades</a><ul>
<li class="chapter" data-level="9.1" data-path="estimacao-de-densidades.html"><a href="estimacao-de-densidades.html#introducao-3"><i class="fa fa-check"></i><b>9.1</b> Introdução</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="modelos-hierarquicos.html"><a href="modelos-hierarquicos.html"><i class="fa fa-check"></i><b>10</b> Modelos Hierárquicos</a><ul>
<li class="chapter" data-level="10.1" data-path="modelos-hierarquicos.html"><a href="modelos-hierarquicos.html#introducao-4"><i class="fa fa-check"></i><b>10.1</b> Introdução</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="nao-resposta.html"><a href="nao-resposta.html"><i class="fa fa-check"></i><b>11</b> Não-Resposta</a><ul>
<li class="chapter" data-level="11.1" data-path="nao-resposta.html"><a href="nao-resposta.html#introducao-5"><i class="fa fa-check"></i><b>11.1</b> Introdução</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="diagnostico-de-ajuste-de-modelo.html"><a href="diagnostico-de-ajuste-de-modelo.html"><i class="fa fa-check"></i><b>12</b> Diagnóstico de ajuste de modelo</a><ul>
<li class="chapter" data-level="12.1" data-path="diagnostico-de-ajuste-de-modelo.html"><a href="diagnostico-de-ajuste-de-modelo.html#introducao-6"><i class="fa fa-check"></i><b>12.1</b> Introdução</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="agregdesag.html"><a href="agregdesag.html"><i class="fa fa-check"></i><b>13</b> Agregação vs. Desagregação</a><ul>
<li class="chapter" data-level="13.1" data-path="agregdesag.html"><a href="agregdesag.html#introducao-7"><i class="fa fa-check"></i><b>13.1</b> Introdução</a></li>
<li class="chapter" data-level="13.2" data-path="agregdesag.html"><a href="agregdesag.html#modelagem-da-estrutura-populacional"><i class="fa fa-check"></i><b>13.2</b> Modelagem da Estrutura Populacional</a></li>
<li class="chapter" data-level="13.3" data-path="agregdesag.html"><a href="agregdesag.html#modelos-hierarquicos-1"><i class="fa fa-check"></i><b>13.3</b> Modelos Hierárquicos</a></li>
<li class="chapter" data-level="13.4" data-path="agregdesag.html"><a href="agregdesag.html#analise-desagregada-pros-e-contras"><i class="fa fa-check"></i><b>13.4</b> Análise Desagregada: Prós e Contras</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="pacotes.html"><a href="pacotes.html"><i class="fa fa-check"></i><b>14</b> Pacotes para Analisar Dados Amostrais</a><ul>
<li class="chapter" data-level="14.1" data-path="pacotes.html"><a href="pacotes.html#introducao-8"><i class="fa fa-check"></i><b>14.1</b> Introdução</a></li>
<li class="chapter" data-level="14.2" data-path="pacotes.html"><a href="pacotes.html#pacotes-computacionais"><i class="fa fa-check"></i><b>14.2</b> Pacotes Computacionais</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referências</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análise de Dados Amostrais Complexos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="capplanamo" class="section level1">
<h1><span class="header-section-number">Capítulo 3</span> Estimação Baseada no Plano Amostral</h1>
<div id="estimatotais" class="section level2">
<h2><span class="header-section-number">3.1</span> Estimação de Totais</h2>
<p>Devido a sua importância para os desenvolvimentos teóricos em vários dos capítulos subsequentes, alguns resultados básicos relativos à estimação de totais da população finita numa abordagem baseada no plano amostral serão reproduzidos nesta seção. A referência básica usada foi a Seção 2.8 de <span class="citation">(Särndal, Swensson, and Wretman <a href="#ref-SSW92">1992</a>)</span>.</p>
<p>Consideremos o problema de estimar o vetor <span class="math inline">\(\mathbf{Y}=\sum_{i \in U}\mathbf{y}_i\)</span> de totais das <span class="math inline">\(P\)</span> variáveis da pesquisa na população, a partir de uma amostra observada <span class="math inline">\(a\)</span>. Naturalmente, qualquer estimador viável do total <span class="math inline">\(\mathbf{Y}\)</span> só pode depender dos valores das variáveis de pesquisa observados na amostra, contidos em <span class="math inline">\(\mathbf{y}_{i_{1}}, \ldots , \mathbf{y}_{i_{n}}\)</span>, mas não dos valores dessas variáveis para os elementos não pesquisados.</p>
<p>Um estimador usual baseado no plano amostral para o total <span class="math inline">\(\mathbf{Y}\)</span> é o estimador de Horvitz-Thompson, também chamado  <span class="math inline">\(\pi\)</span>  (veja p.42 de <span class="citation">(Särndal, Swensson, and Wretman <a href="#ref-SSW92">1992</a>)</span>), dado por:</p>
<span class="math display" id="eq:estpa1">\[\begin{equation}
\hat{\mathbf{Y}}_\pi = \sum_{i \in a} \mathbf{y}_i / \pi_{i} . \tag{3.1}
\end{equation}\]</span>
<p>Na abordagem baseada no planejamento amostral, as propriedades de uma estatística ou estimador são avaliadas com respeito à distribuição de aleatorização. Denotemos por <span class="math inline">\(E_p(.)\)</span> e <span class="math inline">\(V_p(.)\)</span> os operadores de esperança e variância referentes à distribuição de probabilidades <span class="math inline">\(p(a)\)</span> induzida pelo planejamento amostral, que chamaremos daqui por diante de <code>esperança  de aleatorização</code> e <code>variância de aleatorização</code>.</p>
<p>O estimador <span class="math inline">\(\pi\)</span>-ponderado <span class="math inline">\(\mathbf{\hat{Y}}_{\pi}\)</span> é não-viciado para o total <span class="math inline">\(\mathbf{Y}\)</span> com respeito à distribuição de aleatorização, isto é</p>
<p><span class="math display">\[
E_p \left( \mathbf{\hat{Y}}_{\pi} \right) = \mathbf{Y} . 
\]</span> Além disto, sua variância de aleatorização é dada por</p>
<span class="math display" id="eq:estpa2">\[\begin{equation}
V_p \left( \mathbf{\hat{Y}}_{\pi} \right) = \sum_{ i \in U} \, \sum_{j \in U} \left( \pi _{ij} - \pi_i \pi_j \right) \frac{ \mathbf{y}_i} {\pi_i} \frac{\mathbf{y}_j ^{\prime} } {\pi_j} \; .  \tag{3.2}
\end{equation}\]</span>
<p>Uma expressão alternativa da variância de aleatorização de <span class="math inline">\(\mathbf{\hat{Y}}_{\pi}\)</span> , válida quando o plano amostral é de tamanho fixo, é dada por</p>
<span class="math display" id="eq:estpa3">\[\begin{equation}
V_p \left( \mathbf{\hat{Y}}_{\pi} \right) = -\frac{1}{2} \sum_{i \in U} \, \sum_{j \in U} \left( \pi_{ij} - \pi_i \pi_j \right) \left( \frac{\mathbf{y}_i} {\pi_i} - \frac{\mathbf{y}_j} {\pi_j} \right) \left( \frac{\mathbf{y}_i} {\pi_i} - \frac{\mathbf{y}_j} {\pi_j} \right) ^{^{\prime}}.  \tag{3.3}
\end{equation}\]</span>
<p>Note que na expressão <a href="capplanamo.html#eq:estpa3">(3.3)</a> os termos onde <span class="math inline">\(i=j\)</span> não contribuem para a soma. Dois estimadores são usualmente recomendados para estimar a variância de aleatorização de <span class="math inline">\(\mathbf{\hat{Y}}_{\pi}\)</span>. O primeiro é motivado pela expressão <a href="capplanamo.html#eq:estpa2">(3.2)</a> e é dado por</p>
<span class="math display" id="eq:estpa4">\[\begin{equation}
\hat{V}_p \left( \mathbf{\hat{Y}}_{\pi} \right) = \sum_{i \in a} \, \sum_{j \in a} \frac{\pi_{ij} - \pi_i \pi_j} {\pi_{ij}} \frac{\mathbf{y}_i} {\pi_i} \frac{\mathbf{y}_j^{^{\prime}}} {\pi_j} \mbox{.}  \tag{3.4}
\end{equation}\]</span>
<p>O estimador de variância em <a href="capplanamo.html#eq:estpa4">(3.4)</a> é um estimador não-viciado da variância de aleatorização de <span class="math inline">\(\mathbf{\hat{Y}}_{\pi}\)</span>, isto é</p>
<span class="math display" id="eq:estpa5">\[\begin{equation}
E_p \left[ \hat{V}_p \left( \mathbf{\hat{Y}}_{\pi} \right) \right] = V_p \left( \mathbf{\hat{Y}}_{\pi} \right) \tag{3.5}
\end{equation}\]</span>
<p>desde que <span class="math inline">\(\pi _{ij} &gt; 0 \quad \forall i,j \in U\)</span>, como suposto neste livro na Seção <a href="refinf.html#planamo">2.4</a>.</p>
<p>O segundo estimador da variância, chamado estimador de Sen-Yates-Grundy, é motivado pela expressão <a href="capplanamo.html#eq:estpa3">(3.3)</a> e é dado por</p>
<span class="math display" id="eq:estpa6">\[\begin{equation}
\hat{V}_{SYG} \left( \mathbf{\hat{Y}}_{\pi} \right) = - \frac{1}{2} \sum_{i \in a} \, \sum_{j \in a} \frac{\pi _{ij} - \pi_i \pi_j} {\pi_{ij}} \left( \frac{
\mathbf{y}_i} {\pi_i} - \frac{\mathbf{y}_j} {\pi_j} \right) \left( 
\frac{\mathbf{y}_i} {\pi_i} - \frac{\mathbf{y}_j} {\pi_j} \right)^{^{\prime }}.  \tag{3.6}
\end{equation}\]</span>
<p>Observe que embora as expressões da variância <a href="capplanamo.html#eq:estpa2">(3.2)</a> e <a href="capplanamo.html#eq:estpa3">(3.3)</a> coincidam para planos amostrais de tamanho fixo, o mesmo não vale para os estimadores de variância <a href="capplanamo.html#eq:estpa4">(3.4)</a> e <a href="capplanamo.html#eq:estpa6">(3.6)</a>, apesar de <span class="math inline">\(\hat{V}_{SYG} \left( \mathbf{\hat{Y}}_{\pi} \right)\)</span> ser também não-viciado para <span class="math inline">\(V_{p} \left( \mathbf{\hat{Y}}_{\pi} \right)\)</span> para planos amostrais de tamanho fixo.</p>

<div class="example">
<span id="ex:unnamed-chunk-52" class="example"><strong>Exemplo 3.1 </strong></span>Amostragem Aleatória Simples Sem Reposição (AAS)
</div>
<p></p>
<p>Quando o plano é amostragem aleatória simples sem reposição (AAS), as expressões apresentadas para o estimador de total, sua variância e estimadores desta variância simplificam bastante, porque as probabilidades de inclusão ficam iguais a <span class="math display">\[
\pi_i = \frac{n}{N}\ \ \forall \ \ i \in U \mbox{,} 
\]</span> e <span class="math display">\[
\pi_{ij} = \frac{n(n-1)}{N(N-1)}\ \ \forall \ \ i \neq j \in U\;. 
\]</span></p>
<p>Essas probabilidades de inclusão levam às seguintes expressões para o caso AAS:</p>
<span class="math display" id="eq:estpa7">\[\begin{equation}
\hat{\mathbf{Y}}_{AAS} = \frac{N}{n} \sum_{i \in a} \mathbf{y}_i = N \overline{\mathbf{y}} \mbox{ ,}  \tag{3.7}
\end{equation}\]</span>
<span class="math display" id="eq:estpa8">\[\begin{equation}
V_{AAS} \left( \mathbf{\hat{Y}}_{\pi} \right) = N^{2} \frac{1-f}{n} \frac{N}{N-1}
\mathbf{S}_y \mbox{ ,}  \tag{3.8}
\end{equation}\]</span>
<span class="math display" id="eq:estpa9">\[\begin{equation}
\hat{V}_p \left( \mathbf{\hat{Y}}_{AAS} \right) = \hat{V}_{SYG} \left( 
\mathbf{\hat{Y}}_{AAS} \right) = N^{2} \frac{1-f}{n} \frac{n}{n-1} \mathbf{\hat{S}}_y \mbox{ ,} \tag{1.1}
\end{equation}\]</span>
<p>onde <span class="math inline">\(f=n/N\)</span> é a fração amostral e</p>
<span class="math display" id="eq:estpa10">\[\begin{equation}
\overline{\mathbf{y}} = n^{-1} \sum_{i \in a} \mathbf{y}_i \mbox{ ,} \tag{3.9}
\end{equation}\]</span>
<span class="math display" id="eq:estpa11">\[\begin{equation}
\mathbf{S}_y = N^{-1} \sum_{i \in U} \left( \mathbf{y}_i - \overline{\mathbf{Y}}
\right) \left( \mathbf{y}_i - \overline{\mathbf{Y}} \right) ^{^{\prime }} \mbox{ ,}  \tag{3.10}
\end{equation}\]</span>
<span class="math display" id="eq:estpa12">\[\begin{equation}
\overline{\mathbf{Y}} = N^{-1} \sum_{i \in U} \mathbf{y}_i = N^{-1} \mathbf{Y} \mbox{ ,}  \tag{3.11}
\end{equation}\]</span>
<span class="math display" id="eq:estpa13">\[\begin{equation}
\widehat{\mathbf{S}}_y = n^{-1} \sum_{i \in a} \left( \mathbf{y}_i - \overline{\mathbf{y}} \right) \left( \mathbf{y}_i - \overline{\mathbf{y}} \right) ^{^{\prime }} \;. \tag{3.12} 
\end{equation}\]</span>
<p>Vários estimadores de totais estão disponíveis na literatura de amostragem, porém os que são comumente usados na prática são estimadores ponderados (lineares) da forma</p>
<span class="math display" id="eq:estpa14">\[\begin{equation}
\mathbf{\hat{Y}}_w = \sum\limits_{i \in a} w_i \mathbf{y}_i  \tag{3.13}
\end{equation}\]</span>
<p>onde <span class="math inline">\(w_i\)</span> é um peso associado à unidade <span class="math inline">\(i\)</span> da amostra (<span class="math inline">\(i \in a\)</span>). O estimador <span class="math inline">\(\pi\)</span> ou de  é um caso particular de <span class="math inline">\(\mathbf{\hat{Y}}_w\)</span> em <a href="capplanamo.html#eq:estpa14">(3.13)</a> quando os pesos <span class="math inline">\(w_i\)</span> são da forma</p>
<p><span class="math display">\[
w_i^{HT} = \pi_i ^{-1} \quad \forall \ \ i \in a. 
\]</span></p>
<p>Outros dois estimadores de totais comumente usados pelos praticantes de amostragem são o estimador de razão <span class="math inline">\(\mathbf{\hat{Y}}_R\)</span> e o estimador de regressão <span class="math inline">\(\mathbf{\hat{Y}}_{REG}\)</span>, dados respectivamente por</p>
<span class="math display" id="eq:estpa15">\[\begin{equation}
\mathbf{\hat{Y}}_R = \left( \sum_{i \in a} {\ \pi_i^{-1}} \mathbf{y}_i \right) \times \left( \sum_{i \in U}x_i \right) / \left( \sum_{i \in a} {\ \pi_i^{-1}} x_i \right)  \tag{3.14}
\end{equation}\]</span>
<p>e</p>
<span class="math display" id="eq:estpa16">\[\begin{equation}
\mathbf{\hat{Y}}_{REG} = \sum\limits_{i \in a} {\pi_i^{-1}} \mathbf{y}_i + \left( \sum\limits_{i \in U} x_i - \sum\limits_{i \in a} {\pi_i^{-1}} x_i \right) b_{xy}  \tag{3.15}
\end{equation}\]</span>
<p>onde <span class="math inline">\(x\)</span> é uma variável auxiliar cujo total populacional <span class="math inline">\(\sum_{i \in U} x_i = X\)</span> é conhecido e <span class="math inline">\(b_{xy}\)</span> é um estimador dos coeficientes da regressão linear entre as variáveis de pesquisa <span class="math inline">\(\mathbf{y}\)</span> e a variável auxiliar <span class="math inline">\(x\)</span>.</p>
<p>Ambos os estimadores <span class="math inline">\(\mathbf{\hat{Y}}_R\)</span> e <span class="math inline">\(\mathbf{\hat{Y}}_{REG}\)</span> podem ser escritos na forma <span class="math inline">\(\mathbf{\hat{Y}}_w = \sum\limits_{i \in a} w_i \mathbf{y}_i\)</span> com pesos <span class="math inline">\(w_i\)</span> dados respectivamente por</p>
<span class="math display" id="eq:estpa17">\[\begin{equation}
w_i^R = \frac{\pi_i^{-1} \sum_{k \in U} x_k} {\sum\limits_{k \in a} \pi_k^{-1} x_k} = \frac{\pi_i^{-1} X} {\widehat{X}_{\pi}} \tag{3.16} 
\end{equation}\]</span>
<p>e</p>
<span class="math display" id="eq:estpa18">\[\begin{equation}
w_i^{REG} = \pi_i^{-1} g_i \mbox{ ,} \tag{3.17}
\end{equation}\]</span>
<p>onde <span class="math inline">\(\widehat{X}_{\pi} = \sum\limits_{i \in a} \pi_i^{-1} x_i\)</span> é o estimador <span class="math inline">\(\pi\)</span> -ponderado de <span class="math inline">\(X\)</span> e <span class="math inline">\(g_{i} = 1 + x_{i \mbox{ }} (X - \widehat{X}_{\pi}) / \sum_{i \in a} \pi_i^{-1} x_i^2\)</span> .</p>
<p>O estimador de regressão descrito em <a href="capplanamo.html#eq:estpa16">(3.15)</a> é um caso particular do estimador de regressão generalizado, obtido quando se consideram vetores de variáveis auxiliares em vez de uma única variável auxiliar <span class="math inline">\(x\)</span> como aqui. Outra forma de generalizar o estimador de regressão é considerar estimadores alternativos dos coeficientes de regressão em lugar do estimador simples <span class="math inline">\(b_{xy}\)</span> empregado aqui. Para uma discussão detalhada do estimador de regressão generalizado veja <span class="citation">(Nascimento Silva <a href="#ref-Silva">1996</a>)</span>, Cap.3.</p>
<p>Para completar a descrição dos procedimentos de inferência para médias e totais baseados em estimadores ponderados do tipo razão ou regressão, é necessário identificar estimadores para as variâncias de aleatorização correspondentes. Entretanto, os estimadores de razão e regressão são viciados sob a distribuição de aleatorização para pequenas amostras. Em ambos os casos, o vício é desprezível para amostras grandes, e estão disponíveis expressões assintóticas para as respectivas variâncias de aleatorização. Partindo destas foram então construídos estimadores amostrais das variâncias dos estimadores de razão e regressão, que podem ser encontrados na excelente revisão sobre o tema contida em <span class="citation">(Särndal, Swensson, and Wretman <a href="#ref-SSW92">1992</a>)</span>, Seção 6.6 e cap. 7. Apesar de sua importância para os praticantes de amostragem, a discussão detalhada desse problema não será incluída neste livro.</p>
<p>O problema da estimação das variâncias de aleatorização para estimadores como os de razão e regressão nos remete a uma questão central da teoria da amostragem. Trata-se dos métodos disponíveis para estimar variâncias de estimadores <code>complexos</code>. O caso dos estimadores de razão e regressão para totais e médias foi resolvido faz tempo, e não há muito o que discutir aqui. Entretanto, a variedade de métodos empregados para estimação de variâncias merece uma discussão em separado, pois as técnicas de ajuste consideradas neste livro para incorporar pesos e plano amostral na inferência partindo de dados de pesquisas amostrais complexas depende em grande medida da aplicação de tais técnicas.</p>
</div>
<div id="por-que-estimar-variancias" class="section level2">
<h2><span class="header-section-number">3.2</span> Por que Estimar Variâncias</h2>
<p>Em Amostragem, como de resto na Estatística Clássica, a estimação de variâncias é um componente <code>essencial</code> da abordagem inferencial adotada: sem estimativas de variância, nenhuma indicação da precisão (e portanto, da qualidade) das estimativas de interesse está disponível. Nesse caso, uma tentação que assola muitos usuários incautos é esquecer que os resultados são baseados em dados apenas de uma amostra da população, e portanto sujeitos a incerteza, que não pode ser quantificada sem medidas de precisão amostral.</p>
<p>Em geral, a obtenção de estimativas de variâncias (alternativamente, de desvios padrões ou mesmo de coeficientes de variação) é requerida para que intervalos de confiança possam ser calculados, e outras formas de inferência realizadas. Intervalos de confiança elaborados com estimativas amostrais são geralmente baseados em aproximações assintóticas da distribuição normal, tais que intervalos da forma <span class="math display">\[
IC\left[ \widehat{\theta };\widehat{V}_{p}\left( \widehat{\theta }\right)
\right] =\left[ \widehat{\theta }\pm z_{\alpha /2}\sqrt{\widehat{V}%
_{p}\left( \widehat{\theta }\right) }\right] 
\]</span> têm probabilidade de cobertura aproximada <span class="math inline">\(1-\alpha\)</span>.</p>
<p>Estimativas de variância podem ser úteis também para outras finalidades, tais como a detecção de problemas não antecipados, tais como observações suspeitas, celas raras em tabelas de contingência, etc.</p>
<p>A estimação de variâncias para os casos padrões de amostragem, isto é, quando os estimadores são lineares nas observações amostrais, não viciados, e todas as probabilidades de inclusão conjuntas são não nulas, é tratada em todos os livros de amostragem convencionais. Apesar disso, os pacotes estatísticos usuais, tais como SAS, SPSS, MINITAB, BMDP e outros, não oferecem rotinas prontas para estimar variâncias considerando o plano amostral, nem mesmo para estatísticas simples como estimadores de totais e médias.</p>
<p>Para alguns planos amostrais utilizados na prática, as probabilidades de inclusão conjuntas podem ser nulas (caso de amostragem sistemática) ou difíceis de calcular (caso de alguns esquemas de seleção com probabilidades desiguais). Nesses casos, as expressões fornecidas na Seção <a href="capplanamo.html#estimatotais">3.1</a> para os estimadores das variâncias dos estimadores de totais não são mais válidas.</p>
<p>Em muitos outros casos, como se verá no restante deste livro, os parâmetros de interesse são <code>não lineares</code> (diferentes de totais, médias e proporções, por exemplo). Casos comuns que consideraremos mais adiante são a estimação de razões, coeficientes de regressão, etc. Nesses casos é comum que as estatísticas empregadas para estimar tais parâmetros também sejam <code>não lineares</code>.</p>
<p>Finalmente, alguns estimadores de variância podem, em alguns casos, produzir estimativas negativas da variância, que são inaceitáveis de um ponto de vista prático (tais como o estimador da expressão <a href="capplanamo.html#eq:estpa5">(3.5)</a> para alguns esquemas de seleção com probabilidades desiguais e determinadas configurações peculiares da amostra).</p>
<p>Em todos esses casos, é requerido o emprego de técnicas especiais de estimação de variância. é de algumas dessas técnicas que tratam as seções seguintes deste capítulo. A seleção das técnicas discutidas aqui não é exaustiva, e um tratamento mais completo e aprofundado da questão pode ser encontrado no livro de <span class="citation">(Wolter <a href="#ref-W85">1985</a>)</span>. Discutimos inicialmente a técnica de <code>Linearização de Taylor</code>, em seguida uma abordagem comumente adotada para estimar variâncias para planos amostrais estratificados em vários estágios, com seleção de unidades primárias com probabilidades desiguais, denominada <code>Método do Conglomerado Primário</code> (do inglês <em>Ultimate Cluster</em>, e finalmente se discute brevemente uma técnica baseada na ideia de pseudo-replicações da amostra, denominada <code>Jackknife</code>. A combinação dessas três idéias suporta os desenvolvimentos teóricos dos algoritmos empregados pelos principais pacotes estatísticos especializados em estimação de variâncias de aleatorização (veja discussão no Capítulo <a href="agregdesag.html#agregdesag">13</a>.</p>
</div>
<div id="taylor" class="section level2">
<h2><span class="header-section-number">3.3</span> Linearização de Taylor para Estimar variâncias</h2>
<p>Um problema que ocorre frequentemente é o de estimar um vetor de parâmetros <span class="math inline">\(\mathbf{\theta =}\left( \theta _{1},\ldots ,\theta_{K}\right)\)</span>, que pode ser escrito na forma <span class="math display">\[
\mathbf{\theta }=\mathbf{g}(\mathbf{Y})\;, 
\]</span> onde <span class="math inline">\(\mathbf{Y}=\sum_{i\in U}\mathbf{y}_{i}=(Y_{1},\ldots ,Y_{R})^{^{\prime}}\)</span> é um vetor de totais de <span class="math inline">\(R\)</span> variáveis de pesquisa.</p>
<p>Consideremos estimadores <span class="math inline">\(\pi\)</span>-ponderados de <span class="math inline">\(\mathbf{Y}\)</span>, isto é, estimadores da forma: <span class="math display">\[
\widehat{\mathbf{Y}}_{\pi }=\sum_{i\in s}\mathbf{y}_{i}/\pi _{i}\;. 
\]</span> Poderíamos usar <span class="math inline">\(\mathbf{\hat{\theta}}\)</span> dado por <span class="math display">\[
\mathbf{\hat{\theta}}=\mathbf{g}\left( \widehat{\mathbf{Y}}_{\pi }\right) =\mathbf{g}(\sum_{i\in s}\mathbf{y}_{i}/\pi _{i})\;. 
\]</span> como estimador de <span class="math inline">\(\mathbf{\theta}\)</span>. No caso particular em que <span class="math inline">\(\mathbf{g}\)</span> é uma função linear, é fácil estudar as propriedades de <span class="math inline">\(\mathbf{\hat{\theta}}\)</span>.</p>
<p>Assumindo então que <span class="math inline">\(\mathbf{\theta}\)</span> é da forma</p>
<p><span class="math display">\[
\mathbf{\theta }=\mathbf{AY}\mbox{ ,} 
\]</span> onde <span class="math inline">\(\mathbf{A}\)</span> é uma matriz <span class="math inline">\(K\times R\)</span> de constantes, o estimador <span class="math inline">\(\mathbf{\hat{\theta}}\)</span> de <span class="math inline">\(\mathbf{\theta }\)</span> neste caso seria</p>
<p><span class="math display">\[
\mathbf{\hat{\theta}}=\mathbf{A\hat{Y}}_{\pi }\;\;. 
\]</span></p>
<p>Este estimador é não-viciado e tem variância de aleatorização <span class="math display">\[
V_{p}\left( \mathbf{\hat{\theta}}\right) =\mathbf{A}V_{p}\left( \mathbf{\hat{Y}}_{\pi }\right) \mathbf{A}^{^{\prime }}\mathbf{,} 
\]</span> onde <span class="math inline">\(V_{p}\left( \mathbf{\hat{Y}}_{\pi }\right)\)</span> é dado em <a href="capplanamo.html#eq:estpa2">(3.2)</a> ou <a href="capplanamo.html#eq:estpa3">(3.3)</a>.</p>
<p>Quando <span class="math inline">\(\mathbf{g}\)</span> é não linear, podemos usar a técnica de Linearização de Taylor (ou Método Delta) para obter aproximações assintóticas para a variância de <span class="math inline">\(\mathbf{\hat{\theta}}=\mathbf{g}\left( \widehat{\mathbf{Y}}_{\pi }\right)\)</span>. Para maiores detalhes sobre esse método, veja por exemplo p. 172 de <span class="citation">(Särndal, Swensson, and Wretman <a href="#ref-SSW92">1992</a>)</span>, p. 221 de <span class="citation">(Wolter <a href="#ref-W85">1985</a>)</span> ou p. 486 de <span class="citation">(Bishop, Fienberg, and Holland <a href="#ref-Bishop">1975</a>)</span>.</p>
<p>Vamos considerar a expansão de <span class="math inline">\(\mathbf{g}\left( \mathbf{\hat{Y}}_{\pi }\right)\)</span> em torno de <span class="math inline">\(\mathbf{Y}\)</span>, até o termo de primeira ordem, desprezando o resto, dada por:</p>
<span class="math display" id="eq:estpa19">\[\begin{equation}
\mathbf{\hat{\theta}\simeq \hat{\theta}}_{L}=\mathbf{g(Y)+\Delta g(Y)}\left( 
\mathbf{\hat{Y}}_{\pi }\mathbf{-Y}\right)  \tag{3.18}
\end{equation}\]</span>
<p>onde <span class="math inline">\(\mathbf{\Delta g(Y)}\)</span> é a matriz Jacobiana <span class="math inline">\(K\times R\)</span> cuja r-ésima coluna é <span class="math inline">\(\mathbf{\partial g(Y)/}\partial Y_{r}\)</span>,<br />
para <span class="math inline">\(r=1,\ldots,R\)</span>.</p>
Tomando as variâncias de aleatorização dos dois lados em <a href="capplanamo.html#eq:estpa19">(3.18)</a>, e notando que no lado direito o único termo que tem variância de aleatorização <span class="math inline">\(\mathbf{\Delta g(Y)}\left( \mathbf{\hat{Y}}_{\pi }\mathbf{-Y}\right)\)</span> é uma função linear de <span class="math inline">\(\mathbf{\hat{Y}}_{\pi}\)</span>, segue imediatamente que
<span class="math display" id="eq:estpa20">\[\begin{equation}
V_{p}\left( \mathbf{\hat{\theta}}\right) \mathbf{\simeq \Delta g(Y)}
V_{p}\left( \mathbf{\hat{Y}}_{\pi }\right) \mathbf{\Delta g(Y)}^{^{\prime }}
\tag{3.19}
\end{equation}\]</span>
<p>onde <span class="math inline">\(V_{p}\left( \mathbf{\hat{Y}}_{\pi }\right)\)</span> é dado em <a href="capplanamo.html#eq:estpa2">(3.2)</a>. Um estimador consistente de <span class="math inline">\(V_{p}\left( \mathbf{\hat{\theta}}\right)\)</span> é dado por</p>
<span class="math display" id="eq:estpa21">\[\begin{equation}
\hat{V}_{p}\left( \mathbf{\hat{\theta}}\right) =\mathbf{\Delta g(\hat{Y}}_{\pi }\mathbf{)}\hat{V}_{p}\left( \mathbf{\hat{Y}}_{\pi }\right) \mathbf{\Delta g\mathbf{(\hat{Y}}_{\pi }\mathbf{)}}^{^{\prime }},  \tag{3.20}
\end{equation}\]</span>
<p>onde <span class="math inline">\(\hat{V}_{p}\left( \mathbf{\hat{Y}}_{\pi }\right)\)</span> é dado em <a href="capplanamo.html#eq:estpa4">(3.4)</a>. Um outro estimador consistente seria obtido substituindo <span class="math inline">\(\hat{V}_{p}\left( \mathbf{\hat{Y}}_{\pi }\right)\)</span> por <span class="math inline">\(\hat{V}_{SYG}\left( \mathbf{\hat{Y}}_{\pi }\right)\)</span> dado em <a href="capplanamo.html#eq:estpa6">(3.6)</a> na expressão <a href="capplanamo.html#eq:estpa21">(3.20)</a>.</p>
<p>Linearização de Taylor pode ser trabalhosa, porque para cada parâmetro/estimador de interesse são requeridas derivações e cálculos específicos. Felizmente, grande parte das situações de interesse prático estão hoje cobertas por pacotes estatísticos especializados na estimação de medidas descritivas e parâmetros de modelos, e suas respectivas variâncias de aleatorização empregando o método de linearização, de modo que essa desvantagem potencial tende a se diluir.</p>
<p>Linearização de Taylor pode não ser imediatamente possível, pois as quantidades de interesse podem não ser expressas como funções de totais ou médias populacionais (este é o caso de quantis de distribuições, por exemplo).</p>

<div class="example">
<span id="ex:unnamed-chunk-53" class="example"><strong>Exemplo 3.2 </strong></span>Matriz de covariância para um vetor de razões
</div>
<p></p>
<p>Para ilustrar a aplicação dos resultados anteriores, consideremos o problema de estimar a matriz de covariância de um vetor de razões. Sejam <span class="math inline">\(\mathbf{Y}=\left( Y_{1},\ldots Y_{u}\right) ^{^{\prime }}\)</span> e <span class="math inline">\(\mathbf{X}=\left( X_{1},\ldots ,X_{u}\right) ^{^{\prime }}\)</span> vetores de totais e consideremos o vetor de razões <span class="math inline">\(\mathbf{R=}\left( \frac{Y_{1}}{X_{1}},\ldots ,\frac{Y_{u}}{X_{u}}\right) ^{\prime }.\)</span> Conhecendo estimativas das matrizes <span class="math inline">\(V_{p}\left( \mathbf{\hat{Y}}_{\pi }\right)\)</span>, <span class="math inline">\(V_{p}\left( \mathbf{\hat{X}}_{\pi }\right)\)</span> e <span class="math inline">\(COV_{p}\left( \mathbf{\hat{Y}}_{\pi }\mathbf{;\hat{X}}_{\pi }\right)\)</span>, queremos calcular a matriz de variância de <span class="math display">\[
\widehat{\mathbf{R}}\mathbf{=}\left( \frac{\hat{Y}_{1\pi }}{\hat{X}_{1\pi }},\ldots ,\frac{\hat{Y}_{u\pi }}{\hat{X}_{u\pi }}\right) ^{^{\prime }}. 
\]</span></p>
<p>Consideremos a função <span class="math inline">\(\mathbf{g}:\textbf{R}^{2u}\rightarrow \textbf{R}^{u}\)</span> dada por <span class="math display">\[
\mathbf{g}\left( \mathbf{y},\mathbf{x}\right) =\left( \frac{y_{1}}{x_{1}},\ldots ,\frac{y_{u}}{x_{u}}\right) 
\]</span> onde <span class="math inline">\(\mathbf{y=}\left( y_{1},\ldots ,y_{u}\right) ^{^{\prime }}\)</span> e <span class="math inline">\(\mathbf{x=}\left( x_{1},\ldots,x_{u}\right) ^{^{\prime }}\)</span>. A matriz jacobiana de <span class="math inline">\(\mathbf{g}\left( \mathbf{y},\mathbf{x}\right)\)</span> é a matriz <span class="math inline">\(u\times 2u\)</span> dada por <span class="math display">\[
\mathbf{\Delta g}\left( \mathbf{y},\mathbf{x}\right) =\left[ 
\begin{array}{lll}
diag\left( \frac{1}{x_{1}},\ldots ,\frac{1}{x_{u}}\right) &amp;  &amp; diag\left( -\frac{y_{1}}{x_{1}^{2}},\ldots ,-\frac{y_{u}}{x_{u}^{2}}\right)
\end{array}
\right] \;\mbox{.} 
\]</span></p>
<p>Seja <span class="math inline">\(\mathbf{D}_{\mathbf{x}}=diag(x_{1},\ldots ,x_{u})\)</span> a matriz diagonal de dimensão <span class="math inline">\(u\times u\)</span> formada a partir do vetor <span class="math inline">\(\mathbf{x=}\left( x_{1},\ldots ,x_{u}\right) ^{^{\prime }}\)</span>. Usando essa notação, podemos escrever o vetor <span class="math inline">\(\widehat{\mathbf{R}}\)</span> de estimadores das razões como <span class="math display">\[
\widehat{\mathbf{R}}\mathbf{=}\left( \frac{\hat{Y}_{1\pi }}{\hat{X}_{1\pi }},\ldots ,\frac{\hat{Y}_{u\pi }}{\hat{X}_{u\pi }}\right) ^{^{\prime }}=\mathbf{g}\left( \mathbf{\hat{Y}}_{\pi },\mathbf{\hat{X}}_{\pi }\right)
\]</span> e a correspondente matriz jacobiana como <span class="math display">\[
\mathbf{\Delta g}\left( \mathbf{\hat{Y}}_{\pi },\mathbf{\hat{X}}_{\pi
}\right) =\left[ \begin{array}{lll}
\mathbf{\mathbf{D}_{\widehat{\mathbf{R}}}D}_{\mathbf{\hat{Y}}_{\pi }}^{-1} &amp;\left. {}\right. &amp; \mathbf{-\mathbf{D}_{\widehat{\mathbf{R}}}D}_{\mathbf{\hat{X}}_{\pi }}^{-1}
\end{array}
\right] \;. 
\]</span></p>
A partir deste resultado, aplicando <a href="capplanamo.html#eq:estpa21">(3.20)</a> podemos escrever:
<span class="math display">\[\begin{eqnarray*}
&amp;&amp; 
\begin{array}{lll}
\widehat{V}_{p}\left( \widehat{\mathbf{R}}\right) &amp; \doteq &amp; \left[ 
\begin{array}{lll}
\mathbf{\mathbf{D}_{\widehat{\mathbf{R}}}D}_{\mathbf{\hat{Y}}_{\pi }}^{-1} &amp; 
\left. {}\right. &amp; \mathbf{-\mathbf{D}_{\widehat{\mathbf{R}}}D}_{\mathbf{%
\hat{X}}_{\pi }}^{-1}
\end{array}
\right]
\end{array}
\\
&amp;&amp; 
\begin{array}{lll}
&amp;  &amp; \times \left[ 
\begin{array}{cc}
\widehat{V}_{p}\left( \mathbf{\hat{Y}}_{\pi }\right) &amp; \widehat{COV}%
_{p}\left( \mathbf{\hat{Y}}_{\pi }\mathbf{,\hat{X}}_{\pi }\right) \\ 
\widehat{COV}_{p}\left( \mathbf{\hat{X}}_{\pi }\mathbf{,\hat{Y}}_{\pi
}\right) &amp; \widehat{V}_{p}\left( \mathbf{\hat{X}}_{\pi }\right)
\end{array}
\right]
\end{array}
\\
&amp;&amp; 
\begin{array}{lll}
&amp;  &amp; \times \left[ 
\begin{array}{l}
\mathbf{D}_{\mathbf{\hat{Y}}_{\pi }}^{-1}\mathbf{\mathbf{D}_{\widehat{%
\mathbf{R}}}} \\ 
-\mathbf{D}_{\mathbf{\hat{X}}_{\pi }}^{-1}\mathbf{\mathbf{D}_{\widehat{%
\mathbf{R}}}}
\end{array}
\right]
\end{array}
\;\;.
\end{eqnarray*}\]</span>
Efetuando os produtos das matrizes em blocos obtemos
<span class="math display" id="eq:estpa22">\[\begin{eqnarray}
\widehat{V}_{p}\left( \widehat{\mathbf{R}}\right) &amp;=&amp;\mathbf{\mathbf{D}_{%
\widehat{\mathbf{R}}}}\left[ \mathbf{D}_{\mathbf{\hat{Y}}_{\pi }}^{-1}%
\widehat{V}_{p}\left( \mathbf{\hat{Y}}_{\pi }\right) \mathbf{D}_{\mathbf{%
\hat{Y}}_{\pi }}^{-1}+\mathbf{D}_{\mathbf{\hat{X}}_{\pi }}^{-1}\widehat{V}%
_{p}\left( \mathbf{\hat{X}}_{\pi }\right) \mathbf{D}_{\mathbf{\hat{X}}_{\pi
}}^{-1}\right] \mathbf{\mathbf{D}_{\widehat{\mathbf{R}}}}  \nonumber \\
&amp;&amp;-\mathbf{\mathbf{D}_{\widehat{\mathbf{R}}}}\left[ \mathbf{D}_{\mathbf{\hat{%
Y}}_{\pi }}^{-1}\widehat{COV}_{p}\left( \mathbf{\hat{Y}}_{\pi }\mathbf{,\hat{%
X}}_{\pi }\right) \mathbf{D}_{\mathbf{\hat{X}}_{\pi }}^{-1}\right.
\tag{3.21} \\
&amp;&amp;+\left. \mathbf{D}_{\mathbf{\hat{X}}_{\pi }}^{-1}\widehat{COV}_{p}\left( 
\mathbf{\hat{X}}_{\pi }\mathbf{,\hat{Y}}_{\pi }\right) \mathbf{D}_{\mathbf{%
\hat{Y}}_{\pi }}^{-1}\right] \mathbf{\mathbf{D}_{\widehat{\mathbf{R}}}}\;\;%
\mbox{,}  \nonumber
\end{eqnarray}\]</span>
<p>que fornece o resultado desejado, isto é, uma expressão de estimador para a matriz de variância do estimador <span class="math inline">\(\widehat{\mathbf{R}}\)</span> do vetor de razões de interesse.</p>
</div>
<div id="metodo-do-conglomerado-primario" class="section level2">
<h2><span class="header-section-number">3.4</span> Método do Conglomerado Primário</h2>
<p>A ideia central do <code>Método do Conglomerado Primário</code> (do inglês <code>Ultimate Cluster</code>) para estimação de variâncias para estimadores de totais e médias em planos amostrais de múltiplos estágios, proposto por <span class="citation">(Hansen, Hurwitz, and Madow <a href="#ref-hansen">1953</a>)</span>, é considerar apenas a variação entre informações disponíveis no nível das unidades primárias de amostragem (UPAs), isto é, dos conglomerados primários, e admitir que estes teriam sido selecionados com reposição da população. Esta ideia é simples, porém bastante poderosa, porque permite acomodar uma enorme variedade de planos amostrais, envolvendo estratificação e seleção com probabilidades desiguais (com ou sem reposição) tanto das unidades primárias como das demais unidades de amostragem. Os requisitos fundamentais para permitir a aplicação deste método são que estejam disponíveis estimadores não viciados dos totais da variável de interesse para cada um dos conglomerados primários selecionados, e que pelo menos dois destes sejam selecionados em cada estrato (se a amostra for estratificada no primeiro estágio).</p>
<p>Embora o método tenha sido originalmente proposto para estimação de totais, pode ser aplicado também para estimar (por linearização) quantidades populacionais que possam ser representadas como funções de totais, conforme discutido na Seção <a href="capplanamo.html#taylor">3.3</a>. De fato, esse método fornece a base para vários dos pacotes estatísticos especializados em cálculo de variâncias considerando o plano amostral, tais como SUDAAN, CENVAR, STATA ou PC-CARP (veja discussão no Capítulo 10).</p>
Para descrever o método, considere um plano amostral em vários estágios, no qual <span class="math inline">\(n_{h}\)</span> unidades primárias de amostragem (UPAs) são selecionadas no estrato <span class="math inline">\(h,\)</span> <span class="math inline">\(h=1,\ldots ,H\)</span>. Denotemos por <span class="math inline">\(\pi_{hi}\)</span> a probabilidade de inclusão na amostra da unidade primária de amostragem (conglomerado primário) <span class="math inline">\(i\)</span> do estrato <span class="math inline">\(h\)</span>, e por <span class="math inline">\(\widehat{Y}_{hi}\)</span> um estimador não viciado do total <span class="math inline">\(Y_{hi}\)</span> da variável de pesquisa <span class="math inline">\(y\)</span> no <span class="math inline">\(i\)</span>-ésimo conglomerado primário do estrato <span class="math inline">\(h\)</span>, <span class="math inline">\(h=1,\ldots ,H\)</span>. Então um estimador não viciado do total <span class="math inline">\(Y=\sum_{h=1}^{H}\sum_{i=1}^{N_{h}}Y_{hi}\)</span> da variável de pesquisa <span class="math inline">\(y\)</span> na população é dado por <span class="math display">\[
\widehat{Y}_{CP}=\sum_{h=1}^{H}\sum_{i=1}^{n_{h}}\widehat{Y}_{hi}/\pi _{hi} 
\]</span> e um estimador não viciado da variância de aleatorização correspondente por
<span class="math display" id="eq:estpa23">\[\begin{equation}
\widehat{V}_{p}\left( \widehat{Y}_{CP}\right) =\sum_{h=1}^{H}\frac{n_{h}}{%
n_{h}-1}\sum_{i=1}^{n_{h}}\left( \frac{\widehat{Y}_{hi}}{\pi _{hi}}-\frac{%
\widehat{Y}_{h}}{n_{h}}\right) ^{2}  \tag{3.22}
\end{equation}\]</span>
<p>onde <span class="math inline">\(\widehat{Y}_{h}=\sum_{i=1}^{n_{h}}\widehat{Y}_{hi}/\pi _{hi}\)</span> para <span class="math inline">\(h=1,\ldots ,H\)</span>. (Veja por exemplo, <span class="citation">(Shah et al. <a href="#ref-Sudaan93">1993</a>)</span>, p. 4).</p>
<p>Embora muitas vezes a seleção das unidades primárias possa ter sido feita sem reposição, o estimador de Conglomerados Primários aqui apresentado pode fornecer uma aproximação razoável da correspondente variância de aleatorização. Isso ocorre porque planos amostrais sem reposição são em geral mais eficientes que planos com reposição de igual tamanho. Tal aproximação é largamente utilizada pelos praticantes de amostragem para estimar variâncias de quantidades descritivas usuais tais como totais e médias (com a devida adaptação) devido à sua simplicidade, comparada com a complexidade muito maior envolvida com o emprego de estimadores de variância que tentam incorporar todas as etapas de planos amostrais em vários estágios. Uma discussão sobre a qualidade dessa aproximação e alternativas pode ser encontrada em <span class="citation">(Särndal, Swensson, and Wretman <a href="#ref-SSW92">1992</a>)</span>, p. 153.</p>
</div>
<div id="metodos-de-replicacao" class="section level2">
<h2><span class="header-section-number">3.5</span> Métodos de Replicação</h2>
<p>A ideia de usar métodos indiretos ou de replicação para estimar variâncias em amostragem não é nova. <span class="citation">(Mahalanobis <a href="#ref-Mahala39">1939</a>)</span>, <span class="citation">(Mahalanobis <a href="#ref-Mahala44">1944</a>)</span> e <span class="citation">(Deming <a href="#ref-deming">1956</a>)</span> foram os precursores e muitos desenvolvimentos importantes se seguiram. Hoje em dia várias técnicas baseadas nessa ideia são rotineiramente empregadas por praticantes de amostragem, e inclusive formam a base para pacotes especializados de estimação tais como WesVarPC (veja <span class="citation">(Westat <a href="#ref-Westat">1996</a>)</span>).</p>
<p>A ideia básica é construir a amostra de tamanho <span class="math inline">\(n\)</span> como a união de <span class="math inline">\(G\)</span> amostras de tamanho <span class="math inline">\(n/G\)</span> cada uma, selecionadas de forma independente e usando o mesmo plano amostral, onde <span class="math inline">\(G\)</span> é o número de . Nesse caso, se <span class="math inline">\(\theta\)</span> é o parâmetro-alvo, e <span class="math inline">\(\widehat{\theta}_{g}\)</span> é um estimador não viciado de <span class="math inline">\(\theta\)</span> baseado na <span class="math inline">\(g\)</span>-ésima replicação <span class="math inline">\((g=1,\ldots ,G)\)</span>, segue-se que <span class="math display">\[
\widehat{\theta }_{R}=\frac{1}{G}\sum_{g=1}^{G}\widehat{\theta }_{g} 
\]</span> é um estimador não viciado de <span class="math inline">\(\theta\)</span> e</p>
<span class="math display" id="eq:estpa24">\[\begin{equation}
\widehat{V}_{R}\left( \widehat{\theta }_{R}\right) =\frac{1}{G\left(
G-1\right) }\sum_{g=1}^{G}\left( \widehat{\theta }_{g}-\widehat{\theta }%
_{R}\right) ^{2}  \tag{3.23}
\end{equation}\]</span>
<p>é um estimador não viciado da variância do estimador (de replicação) <span class="math inline">\(\widehat{\theta }_{R}\)</span> .</p>
<p>Note que desde que as replicações sejam construídas de forma independente conforme indicado, os estimadores <span class="math inline">\(\widehat{\theta }_{R}\)</span> e <span class="math inline">\(\widehat{V}_{R}\left( \widehat{\theta }_{R}\right)\)</span> são não viciados qualquer que seja o plano amostral empregado para selecionar a amostra de cada replicação, o que faz desta uma técnica flexível e genérica. Além disso, a abordagem de replicação é bastante geral, pois os estimadores aos quais se aplica não precisam ser necessariamente expressos como funções de totais, como ocorre com a técnica de linearização discutida na Seção <a href="capplanamo.html#taylor">3.3</a>. Apesar destas vantagens, a aplicação prática desta técnica de forma exata é restrita porque em geral é menos eficiente, inconveniente e mais caro selecionar <span class="math inline">\(G\)</span> amostras independentes com o mesmo esquema, se comparado à seleção de uma única amostra de tamanho <span class="math inline">\(n\)</span> diretamente. Além disto, se o número de replicações <span class="math inline">\(G\)</span> for pequeno, o estimador de variância pode ser instável. Uma pesquisa importante e de grande porte em que esta ideia é aplicada exatamente é a pesquisa de preços para formar o índice de Preços ao Consumidor (do inglês <em>Consumer Price Index - CPI</em> do <span class="citation">(Labor Statistics <a href="#ref-USBureau">1984</a>)</span>, p. 22, que utiliza duas replicações (meias amostras) para formar a amostra pesquisada.</p>
<p>Mesmo quando a amostra não foi selecionada exatamente dessa forma, a construção de replicações a posteriori para fins de estimação de variâncias em situações complexas é também uma ideia simples de aplicar, poderosa e flexível, por acomodar uma ampla gama de planos amostrais e situações de estimação de interesse. Quando as replicações são construídas após a pesquisa (a posteriori), mediante repartição (por sorteio) da amostra pesquisada em <span class="math inline">\(G\)</span> grupos mutuamente exclusivos de igual tamanho, estas são chamadas de <code>replicações dependentes</code> ou <code>grupos aleatórios</code> (do inglês <em>random groups</em>). As expressões fornecidas para o estimador de replicação e sua variância são também empregadas nesse caso como uma aproximação, mas não possuem as mesmas propriedades do caso de replicações independentes.</p>
<p>É importante observar que a repartição da amostra em grupos aleatórios a posteriori precisa considerar o plano amostral empregado e pode não ser possível em algumas situações. Idealmente, tal repartição deve ser feita respeitando estratos e alocando unidades primárias inteiras (isto é, com todas as respectivas unidades subordinadas). <span class="citation">(Wolter <a href="#ref-W85">1985</a>)</span>,p. 31], discute algumas regras sobre como fazer para respeitar o plano amostral ao fazer a repartição da amostra a posteriori, porém recomendamos que o interessado no uso dessa técnica exerça cautela.</p>
Além da modificação da interpretação das replicações no caso de serem formadas a posteriori, é comum também nesse caso empregar um estimador para o parâmetro <span class="math inline">\(\theta\)</span> baseado na amostra completa (denotado <span class="math inline">\(\widehat{\theta }\)</span>), e um estimador de variância mais conservador que o estimador <span class="math inline">\(\widehat{V}_{R}\left( \widehat{\theta }_{R}\right)\)</span> anteriormente apresentado, dado por
<span class="math display" id="eq:estpa25">\[\begin{equation}
\widehat{V}_{RG}\left( \widehat{\theta }\right) =\frac{1}{G\left( G-1\right) 
}\sum_{g=1}^{G}\left( \widehat{\theta }_{g}-\widehat{\theta }\right) ^{2}\;.
\tag{3.24}
\end{equation}\]</span>
<p>Um exemplo de aplicação desta técnica pode ser encontrado na forma recomendada para estimação de variâncias a partir das Amostras de Uso Público do Censo Demográfico Brasileiro de 80 (veja <span class="citation">(IBGE <a href="#ref-IBGE85">1985</a>)</span>).</p>
Nesta seção descreveremos uma outra dessas técnicas baseadas em replicações, talvez a mais conhecida e popular, o método de <code>jackknife</code>. Este método foi originalmente proposto por <span class="citation">(Quenoille <a href="#ref-Queno49">1949</a>)</span> e <span class="citation">(Quenoille <a href="#ref-Queno56">1956</a>)</span> como uma técnica para redução de vício de estimadores, num contexto da Estatística Clássica. A ideia central consiste em repartir a amostra (a posteriori, como no caso do método dos grupos aleatórios) em <span class="math inline">\(G\)</span> grupos mutuamente exclusivos de igual tamanho <span class="math inline">\(n/G\)</span>. Em seguida, para cada grupo formado calcular os chamados pseudo-estimadores dados por <span class="math display">\[
\widehat{\theta }_{\left( g\right) }=G\widehat{\theta }-\left( G-1\right) 
\widehat{\theta }_{g} 
\]</span> onde <span class="math inline">\(\widehat{\theta }_{g}\)</span> é um estimador de <span class="math inline">\(\theta\)</span> obtido da amostra após eliminar os elementos do grupo <span class="math inline">\(g\)</span>, empregando a mesma forma funcional adotada no cálculo do estimador <span class="math inline">\(\widehat{\theta}\)</span> que considera a amostra inteira. A estimação da variância por esse método pode então ser feita de duas maneiras alternativas, usando um dos estimadores dados por
<span class="math display" id="eq:estpa26">\[\begin{equation}
\widehat{V}_{J1}\left( \widehat{\theta }\right) =\frac{1}{G\left( G-1\right) 
}\sum_{g=1}^{G}\left( \widehat{\theta }_{\left( g\right) }-\widehat{\theta }%
_{J}\right) ^{2}  \tag{3.25}
\end{equation}\]</span>
ou
<span class="math display" id="eq:estpa27">\[\begin{equation}
\widehat{V}_{J2}\left( \widehat{\theta }\right) =\frac{1}{G\left( G-1\right) 
}\sum_{g=1}^{G}\left( \widehat{\theta }_{\left( g\right) }-\widehat{\theta }%
\right) ^{2}  \tag{3.26}
\end{equation}\]</span>
<p>onde <span class="math inline">\(\widehat{\theta }_{J}=\frac{1}{G}\sum_{g=1}^{G}\widehat{\theta }_{\left( g\right)}\)</span> é um estimador pontual <em>jackknife</em> para <span class="math inline">\(\theta\)</span>, alternativo ao estimador da amostra inteira <span class="math inline">\(\hat{\theta}\)</span>.</p>

<div class="remark">
<span class="remark"><em>Observação </em></span> A descrição do método <em>jackknife</em> aqui apresentada não cobre o caso de planos amostrais estratificados, que é mais complexo. Para detalhes sobre este caso, consulte <span class="citation">(Wolter <a href="#ref-W85">1985</a>)</span>, pág. 174.
</div>
<p></p>

<div class="remark">
<span class="remark"><em>Observação </em></span> O estimador <span class="math inline">\(\widehat{V}_{J2}\left( \widehat{\theta }\right)\)</span> é mais conservador que o estimador <span class="math inline">\(\widehat{V}_{J1}\left( \widehat{\theta }\right)\)</span>.
</div>
<p></p>

<div class="remark">
<span class="remark"><em>Observação </em></span> É comum aplicar a técnica fazendo o número de grupos igual ao tamanho da amostra, isto é, tomando <span class="math inline">\(G=n\)</span> e portanto eliminando uma observação da amostra de cada vez ao calcular os pseudo-valores. Essa regra deve ser aplicada considerando o número de unidades primárias na amostra (UPAs) quando o plano amostral é em múltiplos estágios, pois as UPAs devem sempre ser eliminadas com todas as unidades subordinadas.
</div>
<p></p>
<p>Os estimadores de variância do método <code>jackknife</code> fornecem resultado idêntico aos dos estimadores usuais de variância quando aplicados para o caso de estimadores lineares nas observações amostrais. Além disso, suas propriedades são razoáveis para vários outros casos de estimadores não lineares de interesse (veja, por exemplo, <span class="citation">(Cochran <a href="#ref-cochran">1977</a>)</span>, p. 321 e <span class="citation">(Wolter <a href="#ref-W85">1985</a>)</span>, p. 306. A situação merece maiores cuidados para o caso de quantis ou estatísticas de ordem, tais como a mediana e o máximo, pois neste caso essa técnica não funciona bem <span class="citation">(Wolter <a href="#ref-W85">1985</a>)</span>, p. 163.</p>
<p>O pacote WesVarPC <span class="citation">(Westat <a href="#ref-Westat">1996</a>)</span> baseia suas estimativas de variância principalmente no método <code>jackknife</code>, embora também possua uma opção para usar outro método conhecido como de replicações de meias amostras balanceadas (do inglês <em>balanced half-sample replication</em>).</p>
</div>
<div id="laboratorio-de-r" class="section level2">
<h2><span class="header-section-number">3.6</span> Laboratório de R</h2>
<p>Vamos utilizar dados da Pesquisa de Padrão de Vida (PPV) do IBGE para ilustrar alguns métodos de estimação de variâncias. Vamos considerar a estimação da proporção de analfabetos na faixa etária acima de 14 anos. Os dados da pesquisa encontram-se no data frame . A variável <code>analf2</code> é indicadora da condição de analfabetismo na faixa etária acima de 14 anos e a variável <code>faixa2</code> é indicadora da faixa etária acima de 14 anos. Queremos estimar a proporção de analfabetos na faixa etária acima de 14 anos na região Sudeste. Antes apresentamos o método de estimação de variância por linearização de Taylor</p>
<p>Vamos criar duas variáveis:</p>
<ul>
<li>analf - variável indicadora da condição de analfabetismo: <code>v04a01</code> ou <code>v04a02</code> igual a 2;</li>
<li>faixa - variável indicadora de faixa etária entre 7 e 14 anos.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(survey)
ppv1 &lt;-<span class="kw">readRDS</span>(<span class="st">&quot;~</span><span class="ch">\\</span><span class="st">GitHub</span><span class="ch">\\</span><span class="st">adac</span><span class="ch">\\</span><span class="st">data</span><span class="ch">\\</span><span class="st">ppv.rds&quot;</span>) 
<span class="kw">library</span>(survey)
ppv.des&lt;-<span class="kw">svydesign</span>(<span class="dt">ids =</span> ~nsetor, <span class="dt">strata =</span> ~estratof,
<span class="dt">data =</span> ppv1, <span class="dt">nest =</span> <span class="ot">TRUE</span>, <span class="dt">weights =</span> ~pesof)

ppv.des&lt;-<span class="kw">update</span>(ppv.des,
  <span class="dt">analf=</span>(v04a01 ==<span class="st"> </span><span class="dv">2</span> |<span class="st"> </span>v04a02 ==<span class="st"> </span><span class="dv">2</span>)*<span class="dv">1</span>,
  <span class="dt">faixa=</span>(v02a08 &gt;=<span class="st"> </span><span class="dv">7</span> &amp;<span class="st"> </span>v02a08 &lt;=<span class="st"> </span><span class="dv">14</span>) *<span class="dv">1</span>
)
ppv.se.des &lt;-<span class="st"> </span><span class="kw">subset</span>(ppv.des, regiao ==<span class="st"> </span><span class="dv">2</span>)
ppv.des&lt;-<span class="kw">update</span>(ppv.des,<span class="dt">analf.faixa=</span> (analf==<span class="dv">1</span> &amp;<span class="st"> </span>faixa==<span class="dv">1</span>)*<span class="dv">1</span>)</code></pre></div>
<p>Como estamos interessados em estimativas relativas à Região Sudeste, vamos restringir o desenho a esse domínio:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ppv.se.des &lt;-<span class="st"> </span><span class="kw">subset</span>(ppv.des, regiao ==<span class="st"> </span><span class="dv">2</span>)</code></pre></div>
<p>Vamos estimar os totais das variáveis <code>analf.faixa</code> e <code>faixa</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tot.est&lt;-<span class="kw">svytotal</span>(~analf.faixa+faixa ,ppv.se.des )
Vcov.Y1.Y2&lt;-<span class="kw">vcov</span>(tot.est) </code></pre></div>
<p>Substituindo os valores na expressão <a href="capplanamo.html#eq:estpa21">(3.20)</a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y1hat&lt;-<span class="kw">coef</span>(tot.est)[<span class="dv">1</span>]
y2hat&lt;-<span class="kw">coef</span>(tot.est)[<span class="dv">2</span>]
Var.raz&lt;-(<span class="dv">1</span>/y2hat)*(<span class="dv">1</span>/y2hat)*Vcov.Y1.Y2[<span class="dv">1</span>,<span class="dv">1</span>]+<span class="dv">2</span>*(<span class="dv">1</span>/y2hat)*(-y1hat/y2hat^<span class="dv">2</span>)*Vcov.Y1.Y2[<span class="dv">1</span>,<span class="dv">2</span>]+
(-y1hat/y2hat^<span class="dv">2</span>)*(-y1hat/y2hat^<span class="dv">2</span>)*Vcov.Y1.Y2[<span class="dv">2</span>,<span class="dv">2</span>]
<span class="kw">sqrt</span>(Var.raz)</code></pre></div>
<pre><code>##      faixa 
## 0.01178896</code></pre>
<p>Podemos calcular diretamente o desvio-padrão:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">svyratio</span>(~analf.faixa, ~faixa, ppv.se.des)</code></pre></div>
<pre><code>## Ratio estimator: svyratio.survey.design2(~analf.faixa, ~faixa, ppv.se.des)
## Ratios=
##                faixa
## analf.faixa 0.118689
## SEs=
##                  faixa
## analf.faixa 0.01178896</code></pre>
<p>A estimativa do desvio-padrão obtida por meio da função <code>svyratio</code> coincide com a obtida diretamente pelo método de linearização, e é igual a 0.01179. O método default para estimar variâncias usado pela library <code>survey</code> <span class="citation">(Lumley <a href="#ref-R-survey">2016</a>)</span> do R é o de linearização de Taylor.</p>
<p>A library <code>survey</code> dispõe de métodos alternativos para a estimação de variância. Vamos utilizar os métodos de replicação de <code>Jackknife</code> e de <code>Bootstrap</code> para estimar esta variância de razão. Inicialmente, vamos converter o objeto de desenho <code>ppv1.se.design</code> em um objeto de desenho de replicação de <em>Jackknife</em>, contendo as réplicas de pesos que vão gerar as réplicas de estimativas.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ppv.se.des.jkn&lt;-<span class="kw">as.svrepdesign</span>(ppv.se.des,<span class="dt">type=</span><span class="st">&quot;JKn&quot;</span>)
<span class="kw">svyratio</span>(~analf.faixa, ~faixa, ppv.se.des.jkn)</code></pre></div>
<pre><code>## Ratio estimator: svyratio.svyrep.design(~analf.faixa, ~faixa, ppv.se.des.jkn)
## Ratios=
##                faixa
## analf.faixa 0.118689
## SEs=
##            [,1]
## [1,] 0.01181434</code></pre>
<p>Para o método <code>Bootstrap</code>, temos:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ppv.se.des.boot&lt;-<span class="kw">as.svrepdesign</span>(ppv.se.des,<span class="dt">type=</span><span class="st">&quot;bootstrap&quot;</span>)
<span class="kw">svyratio</span>(~analf.faixa, ~faixa, ppv.se.des.boot)</code></pre></div>
<pre><code>## Ratio estimator: svyratio.svyrep.design(~analf.faixa, ~faixa, ppv.se.des.boot)
## Ratios=
##                faixa
## analf.faixa 0.118689
## SEs=
##            [,1]
## [1,] 0.01264514</code></pre>
<p>Vamos apresentar mais detalhes sobre a obtenção dos estimadores de Jackknife e Bootstrap na library <code>survey</code> <span class="citation">(Lumley <a href="#ref-R-survey">2016</a>)</span>. A classe do objeto <code>ppv.se.des.jkn</code> é <code>svyrep.design</code> e ele contém as seguintes componentes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(ppv.se.des.jkn)</code></pre></div>
<pre><code>## [1] &quot;svyrep.design&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(ppv.se.des.jkn)</code></pre></div>
<pre><code>##  [1] &quot;repweights&quot;       &quot;pweights&quot;         &quot;type&quot;            
##  [4] &quot;rho&quot;              &quot;scale&quot;            &quot;rscales&quot;         
##  [7] &quot;call&quot;             &quot;combined.weights&quot; &quot;selfrep&quot;         
## [10] &quot;mse&quot;              &quot;variables&quot;        &quot;degf&quot;</code></pre>
<p>A componente <code>repweights</code> é uma lista com duas componentes: <code>weights</code> e <code>index</code>. A componente <code>weights</code> é uma matriz de dimensão <span class="math inline">\(276 \times 276\)</span>, onde <span class="math inline">\(276\)</span> é o número de conglomerados primários do plano amostral da PPV na região Sudeste. A partir desta matriz, podemos obter <span class="math inline">\(276\)</span> réplicas de pesos de desenho de Jackknife.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ppv.se&lt;-ppv.se.des.jkn$variables
<span class="kw">nrow</span>(ppv.se)</code></pre></div>
<pre><code>## [1] 8903</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ncong&lt;-<span class="kw">sum</span>(<span class="kw">with</span>(ppv.se,<span class="kw">tapply</span>( nsetor,estratof, function(t) <span class="kw">length</span>(<span class="kw">unique</span>(t)))))
ncong</code></pre></div>
<pre><code>## [1] 276</code></pre>
<p>O argumento <code>compress</code> da função <code>as.svrepdesign</code> permite especificar se, na saída da função, a matriz <code>weights</code> será na forma comprimida ou não. Na aplicação feita foi usado o valor default que é a forma comprimida. A forma não comprimida da matriz <code>weights</code> tem 8903 linhas e 276 colunas. A forma comprimida permite economizar memória, e pode ser facilmente convertida para a forma não comprimida, utilizando-se a componente<code>index</code>.</p>
<p>No método jackknife, cada um dos conglomerados primários é removido, e a réplica correspondente dos pesos é o produto do peso amostral original por um fator apropriado, definido da forma a seguir. Suponhamos que foi removido um conglomerado no estrato <span class="math inline">\(h\)</span>, então os pesos do plano amostral serão multiplicados por:</p>
<ul>
<li><span class="math inline">\(0\)</span> para as unidades no conglomerado removido;</li>
<li><span class="math inline">\(m_h/(m_h-1)\)</span> para unidades pertencentes a outros conglomerados do estrato <span class="math inline">\(h\)</span>;</li>
<li><span class="math inline">\(1\)</span> para unidades em estratos <span class="math inline">\(h&#39;\neq h\)</span>.</li>
</ul>
<p>Podemos obter a matriz de fatores de correção do peso amostral na forma não comprimida da seguinte maneira:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fact.peso.comp&lt;-ppv.se.des.jkn$repweights[[<span class="dv">1</span>]]
ind.cong&lt;-ppv.se.des.jkn$repweights[[<span class="dv">2</span>]]
mat.fat.pesos&lt;-<span class="st"> </span>fact.peso.comp[ind.cong,]
<span class="kw">str</span>(mat.fat.pesos)</code></pre></div>
<pre><code>##  num [1:8903, 1:276] 0 0 1.06 1.06 1.06 ...</code></pre>
<p>Podemos obter matriz de réplicas de pesos multiplicando cada coluna dessa matriz pelos pesos do plano amostra:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat.rep.pesos&lt;-<span class="kw">weights</span>(ppv.se.des)*mat.fat.pesos</code></pre></div>
<p>Utilizando esta matriz de réplicas de pesos, podemos obter réplicas correspondentes de estimativas da razão.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rep.est.raz&lt;-<span class="kw">numeric</span>(<span class="kw">ncol</span>(mat.rep.pesos))
for (i in <span class="dv">1</span>:<span class="kw">ncol</span>(mat.rep.pesos)){
rep.est.raz[i]&lt;-<span class="kw">sum</span>(mat.rep.pesos[,i]*ppv.se$analf.faixa)/<span class="kw">sum</span>(mat.rep.pesos[,i]*ppv.se$faixa)
}</code></pre></div>
<p>A partir destas réplicas de estimativas da razão, finalmente estimamos a variância:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mean.raz&lt;-<span class="kw">mean</span>( rep.est.raz[ppv.se.des.jkn$rscales&gt;<span class="dv">0</span>])
var.jack.raz&lt;-<span class="st"> </span><span class="kw">sum</span>((rep.est.raz-mean.raz)^<span class="dv">2</span>*ppv.se.des.jkn$rscales)*ppv.se.des.jkn$scale
<span class="kw">round</span>(<span class="kw">sqrt</span>(var.jack.raz),<span class="dv">5</span>)</code></pre></div>
<pre><code>## [1] 0.01181</code></pre>
<p>A library <code>survey</code> <span class="citation">(Lumley <a href="#ref-R-survey">2016</a>)</span> fornece uma função para estimar a variância de uma função de totais a partir das réplicas de pesos:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">var.raz.rep&lt;-<span class="kw">withReplicates</span>(ppv.se.des.jkn, function(w,ppv.se) <span class="kw">sum</span>(w*ppv.se$analf.faixa)/<span class="kw">sum</span>(w*ppv.se$faixa))
var.raz.rep </code></pre></div>
<pre><code>##        theta     SE
## [1,] 0.11869 0.0118</code></pre>
<p>Resultado que coincide com a estimativa obtida pela aplicação da função <code>svyratio</code>.</p>
<p>A vantagem de utilizar métodos de replicação é a facilidade com que estimamos a variância de qualquer característica da população, cujo estimador é conhecido. Por exemplo, se quisermos estimar a variância da razão das taxas de analfabetos nas faixas etárias de 0 a 14 anos e acima de 14 anos podemos usar as mesmas réplicas de pesos:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">withReplicates</span>(ppv.se.des.jkn,function(w,ppv.se) <span class="kw">with</span>(ppv.se,
(<span class="kw">sum</span>(w*(analf==<span class="dv">1</span>&amp;faixa==<span class="dv">1</span>))/<span class="kw">sum</span>(faixa==<span class="dv">1</span>))/(<span class="kw">sum</span>(w*(analf==<span class="dv">1</span>&amp;faixa==<span class="dv">0</span>))/<span class="kw">sum</span>(faixa==<span class="dv">0</span>))))</code></pre></div>
<pre><code>##        theta     SE
## [1,] 0.50623 0.0494</code></pre>

</div>
</div>
<h3>Referências</h3>
<div id="refs" class="references">
<div id="ref-SSW92">
<p>Särndal, C-E., B. Swensson, and J. H. Wretman. 1992. <em>Model Assisted Survey Sampling</em>. Nova Iorque: Springer-Verlag.</p>
</div>
<div id="ref-Silva">
<p>Nascimento Silva, P. L. D. 1996. “Utilizing Auxiliary Information for Estimation and Analysis in Sample Surveys.” PhD thesis, University of Southampton, Department of Social Statistics.</p>
</div>
<div id="ref-W85">
<p>Wolter, K. M. 1985. <em>Introduction to Variance Estimation</em>. Nova Iorque: Springer-Verlag.</p>
</div>
<div id="ref-Bishop">
<p>Bishop, Y. M. M., S. E. Fienberg, and P. W. Holland. 1975. <em>Discrete Multivariate Analysis: Theory and Practice</em>. Massachusets: The MIT Press.</p>
</div>
<div id="ref-hansen">
<p>Hansen, M. H., W. N. Hurwitz, and W. G. Madow. 1953. <em>Sample Survey Methods and Theory</em>. Nova Iorque: John Wiley; Sons.</p>
</div>
<div id="ref-Sudaan93">
<p>Shah, B. V., R. E. Folsom, L. M. LaVange, S. C. Wheeless, K. E. Boyle, and R. L. Williams. 1993. “Statistical Methods and Mathematical Algorithms Used in Sudaan.”</p>
</div>
<div id="ref-Mahala39">
<p>Mahalanobis, P. C. 1939. “A Sample Survey of the Acreage Under Jute in Bengal.” <em>Sankhya</em> 4: 511–31.</p>
</div>
<div id="ref-Mahala44">
<p>Mahalanobis, P. 1944. “On Large-Scale Sample Surveys.” <em>Philosophical Transactions of the Royal Society of London B</em> 231: 329–451.</p>
</div>
<div id="ref-deming">
<p>Deming, W. E. 1956. “On Simplifications of Sampling Design Through Replication with Equal Probabilities and Without Stages.” <em>Journal of the American Statistical Association</em> 51: 24–53.</p>
</div>
<div id="ref-Westat">
<p>Westat. 1996. <em>A User’s Guide to WesVarPc, Version 2.0</em>. Mariland: Westat, Inc.</p>
</div>
<div id="ref-USBureau">
<p>Labor Statistics, US Bureau of. 1984. “BLS Handbook of Methods - Volume Ii - the Consumer Price Index.” BLS Bulletin 2134-2. Washington DC.</p>
</div>
<div id="ref-IBGE85">
<p>IBGE. 1985. “Amostra de Uso Público Do Censo Demográfico de 1980 - Metodologia E Manual Do Usuário.” Rio de Janeiro: IBGE.</p>
</div>
<div id="ref-Queno49">
<p>Quenoille, M. H. 1949. “Problems in Plane Sampling.” <em>Annals of Mathematical Statistics</em> 20: p. 355–75.</p>
</div>
<div id="ref-Queno56">
<p>Quenoille, M. 1956. “Notes on Bias in Estimation.” <em>Biometrika</em> 43: 353–60.</p>
</div>
<div id="ref-cochran">
<p>Cochran, W. G. 1977. <em>Sampling Techniques</em>. Nova Iorque: John Wiley.</p>
</div>
<div id="ref-R-survey">
<p>Lumley, Thomas. 2016. “Survey: Analysis of Complex Survey Samples.”</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="refinf.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="epa.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/03-Cap3.Rmd",
"text": "Edit"
},
"download": ["bookdown-demo.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
